import { FileWarning } from 'lucide-react';
import { Card } from '../../components/Card';

export function PreliminaryReportsScreen() {
  return (
    <div className="mx-auto max-w-4xl space-y-6">
      <header>
        <p className="text-xs font-bold uppercase tracking-[0.18em] text-forge-teal-700">Server report service</p>
        <h1 className="mt-2 text-3xl font-bold text-foreground">Reports</h1>
        <p className="mt-2 max-w-3xl text-muted-foreground">
          Reports are generated by the authenticated backend PDF pipeline. Browser print-to-PDF generation is intentionally disabled.
        </p>
      </header>
      <Card title="Server-side report generation unavailable">
        <div className="flex gap-3 rounded border border-border bg-muted p-4" role="status">
          <FileWarning className="mt-0.5 h-5 w-5 shrink-0 text-muted-foreground" aria-hidden="true" />
          <div>
            <p className="font-semibold text-foreground">The report worker is not active for this environment.</p>
            <p className="mt-1 text-sm text-muted-foreground">
              No browser-generated substitute will be offered. Re-enable the server-side PDF export service to create an auditable report.
            </p>
          </div>
        </div>
      </Card>
    </div>
  );
}
